name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run linting
        if: always()
        run: npm run lint:ts

      - name: Run unit tests
        if: always()
        run: npm run test:unit

      - name: Build project
        if: always()
        run: npm run build:prod

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-files
          path: path/to/built/files

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Deploy to production
        run: |
          # Add your deployment steps here
          # For example:
          # - Configure server settings
          # - Copy built files to server
          # - Restart server
